# Generated by Django 3.2.13 on 2022-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='writing_down',
            field=models.BooleanField(default=False),
        ),
    ]
