# Generated by Django 3.2.13 on 2022-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='caring_time',
        ),
        migrations.RemoveField(
            model_name='care',
            name='etc',
        ),
        migrations.AlterField(
            model_name='care',
            name='caring_animal',
            field=models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지')], default='', max_length=20),
        ),
    ]
