# Generated by Django 3.2.13 on 2022-12-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Care',
            new_name='care',
        ),
    ]
