# Generated by Django 3.2.13 on 2022-12-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='area',
            field=models.CharField(choices=[('경기도', '경기도'), ('서울시', '서울시'), ('부산광역시', '부산광역시'), ('경상남도', '경상남도'), ('인천광역시', '인천광역시'), ('경상북도', '경상북도'), ('대구광역시', '대구광역시'), ('충청남도', '충청남도'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('충청북도', '충청북도'), ('강원도', '강원도'), ('대전광역시', '대전광역시'), ('광주광역시', '광주광역시'), ('울산광역시', '울산광역시'), ('제주도', '제주도'), ('세종시', '세종시')], default='선택', max_length=100),
        ),
    ]
