# Generated by Django 3.2.13 on 2022-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='caring_animal',
            field=models.CharField(default='', max_length=300, verbose_name='caring_animal'),
        ),
        migrations.AlterField(
            model_name='care',
            name='caring_time',
            field=models.CharField(max_length=300, verbose_name='caring_time'),
        ),
        migrations.AlterField(
            model_name='care',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='care',
            name='etc',
            field=models.CharField(max_length=300, verbose_name='etc'),
        ),
        migrations.AlterField(
            model_name='care',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
