# Generated by Django 3.2.13 on 2022-12-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0002_care_writing_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='caring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caring', to=settings.AUTH_USER_MODEL),
        ),
    ]
