# Generated by Django 3.2.13 on 2022-12-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_auto_20221207_2154'),
        ('care', '0003_rename_pet_gender_care_gender'),
    ]

    operations = [
    ]
