# Generated by Django 3.2.13 on 2022-12-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_care_caring'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='care.care'),
        ),
    ]
