# Generated by Django 3.2.13 on 2022-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_alter_care_caring_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='caring_animal',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='care',
            name='caring_time',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='care',
            name='etc',
            field=models.CharField(max_length=300),
        ),
    ]
