# Generated by Django 3.2.13 on 2022-12-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_auto_20221202_1823'),
        ('care', '0005_auto_20221203_2219'),
    ]

    operations = [
    ]
