# Generated by Django 3.2.13 on 2022-12-11 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_board', models.CharField(choices=[('일기', '일기'), ('산책일기', '산책일기'), ('건강일기', '건강일기')], default='선택', max_length=20)),
                ('route', models.TextField()),
                ('consumed_calories', models.IntegerField()),
                ('walking_time', models.IntegerField()),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/daily_journal/')),
                ('meals', models.CharField(max_length=100)),
                ('energy', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dogwalkingjournal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthjournal',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyJournal',
        ),
        migrations.DeleteModel(
            name='DogwalkingJournal',
        ),
        migrations.DeleteModel(
            name='HealthJournal',
        ),
    ]
