# Generated by Django 3.2.13 on 2022-12-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyjournal',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='dogwalkingjournal',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='healthjournal',
            name='pet',
        ),
    ]
