# Generated by Django 3.2.13 on 2022-12-11 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_auto_20221211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='consumed_calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='energy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='meals',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='medicine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='route',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='walking_time',
            field=models.IntegerField(null=True),
        ),
    ]
