# Generated by Django 3.2.13 on 2022-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_dailyjournal_dogwalkingjournal_healthjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthjournal',
            name='medicine',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
