# Generated by Django 3.2.13 on 2022-12-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0003_auto_20221211_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.pet'),
            preserve_default=False,
        ),
    ]
