# Generated by Django 3.2.13 on 2022-11-29 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_community_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='like',
        ),
        migrations.AddField(
            model_name='community',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
