# Generated by Django 3.2.13 on 2022-12-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='pet_species',
            field=models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이')], default='선택', max_length=20),
        ),
    ]
