# Generated by Django 3.2.13 on 2022-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community',
            field=models.CharField(choices=[('자유게시판', '자유게시판'), ('후기게시판', '후기게시판'), ('질문게시판', '질문게시판')], default='선택', max_length=20),
        ),
    ]
