# Generated by Django 3.2.13 on 2022-11-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='neutralization',
            field=models.CharField(choices=[(None, '선택'), ('Y', '중성화 완료'), ('N', '중성화 전')], default='선택', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petgender',
            field=models.CharField(choices=[(None, '선택'), ('M', '남아'), ('W', '여아')], default='선택', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[(None, '선택'), ('dog', '강아지'), ('cat', '고양이')], default='선택', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(None, '선택'), ('M', '남자'), ('W', '여자')], default='선택', max_length=2),
        ),
    ]
