# Generated by Django 3.2.13 on 2022-12-05 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authphone',
            name='id',
        ),
        migrations.AlterField(
            model_name='authphone',
            name='auth_number',
            field=models.IntegerField(verbose_name='인증 번호'),
        ),
        migrations.AlterField(
            model_name='authphone',
            name='phone',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='휴대폰 번호'),
        ),
    ]
