# Generated by Django 3.2.13 on 2022-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221212_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
