# Generated by Django 3.2.13 on 2022-12-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_phone_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authphone',
            name='auth_number',
            field=models.CharField(max_length=11, verbose_name='인증 번호'),
        ),
    ]
