# Generated by Django 3.2.13 on 2022-11-28 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221128_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=25)),
                ('petage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('petgender', models.CharField(choices=[('M', '남아'), ('W', '여아')], max_length=2)),
                ('neutralization', models.CharField(choices=[('Y', '중성화 완료'), ('N', '중성화 전')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocking',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
