# Generated by Django 3.2.13 on 2022-11-30 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petgender',
            field=models.CharField(choices=[(None, '선택'), ('M', '남아'), ('F', '여아')], default='선택', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL),
        ),
    ]
