# Generated by Django 3.2.13 on 2022-12-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authphone_auth_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authphone',
            name='auth_number',
            field=models.IntegerField(verbose_name='인증 번호'),
        ),
    ]
