# Generated by Django 3.2.13 on 2022-12-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocking',
            new_name='block',
        ),
    ]
