# Generated by Django 3.2.13 on 2022-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_authphone_auth_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authphone',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='pet',
            name='characteristics',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='authphone',
            table='auth',
        ),
    ]
