# Generated by Django 3.2.13 on 2022-12-01 00:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/accounts/'),
        ),
    ]
