# Generated by Django 3.2.13 on 2022-12-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221207_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthPhone',
            new_name='SMSAuthRequest',
        ),
        migrations.AlterModelTable(
            name='smsauthrequest',
            table='sms_auth_requests',
        ),
    ]
