# Generated by Django 3.2.13 on 2022-12-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221207_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMSAuthRequest',
            new_name='AuthPhone',
        ),
        migrations.AlterModelTable(
            name='authphone',
            table='auth',
        ),
    ]
