# Generated by Django 3.2.13 on 2022-12-01 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_pet_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocking',
            field=models.ManyToManyField(related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
