# Generated by Django 3.2.13 on 2022-12-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221201_1748'),
        ('accounts', '0008_user_blocking'),
    ]

    operations = [
    ]
