# Generated by Django 3.2.13 on 2022-12-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20221208_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breeds',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(default='선택', max_length=3),
        ),
    ]
