# Generated by Django 3.2.13 on 2022-12-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221208_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
