# Generated by Django 3.2.13 on 2022-12-10 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogwalking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalking',
            name='walking',
            field=models.ManyToManyField(related_name='walker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dogwalking',
            name='walking_member',
            field=models.IntegerField(default=9),
        ),
    ]
