# Generated by Django 3.2.13 on 2022-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalking',
            name='writing_down',
            field=models.BooleanField(default=False),
        ),
    ]
