# Generated by Django 3.2.13 on 2022-11-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalking',
            name='member',
            field=models.IntegerField(null=True),
        ),
    ]
