# Generated by Django 3.2.13 on 2022-12-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0002_dogwalking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dogwalking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogwalking.dogwalking'),
        ),
    ]
