# Generated by Django 3.2.13 on 2022-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0002_auto_20221211_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalking',
            name='walking_member',
            field=models.IntegerField(default=1, max_length=9),
        ),
    ]
