# Generated by Django 3.2.13 on 2022-11-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0002_dogwalking_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogwalking',
            old_name='member',
            new_name='members',
        ),
    ]
