# Generated by Django 3.2.13 on 2022-11-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0003_rename_member_dogwalking_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogwalking',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
    ]
