# Generated by Django 3.2.13 on 2022-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0002_dogwalking_writing_down'),
        ('dogwalking', '0003_review_dogwalking'),
    ]

    operations = [
    ]
