# Generated by Django 3.2.13 on 2022-11-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0004_auto_20221129_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogwalking',
            name='pet',
        ),
    ]
