# Generated by Django 3.2.13 on 2022-11-29 02:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('dogwalking', '0005_remove_dogwalking_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalking',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
