# Generated by Django 3.2.13 on 2022-11-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogwalking', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Dogwalking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogwalking.dogwalking'),
        ),
    ]
