# Generated by Django 3.2.13 on 2022-12-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendarapp', '0002_alter_event_journal_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.pet'),
            preserve_default=False,
        ),
    ]
