# Generated by Django 3.2.13 on 2022-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='latitude',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='longitude',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
