# Generated by Django 3.2.13 on 2022-12-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20221212_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='information',
            name='longitude',
        ),
    ]
